enabled_backends = ["arch"]

hostname_groups_enabled = true

[hostname_groups]
PLACEHOLDER = [
  "base",
  "utils",
  "audio",
  "graphics",
  "hyprland",
  "desktop",
  "fonts"
]

[arch]
package_manager = "paru"
