arch = [
    # ALSA
    "alsa-firmware",
    "alsa-plugins",
    "alsa-utils",
    "lib32-alsa-plugins",

    # PipeWire
    "pipewire-pulse",
    "pipewire-alsa",
    "pipewire-jack",
    "wireplumber",
    "rtkit",
    "gst-plugin-pipewire",
    "wiremix",
    "lib32-libpipewire",
    "lib32-libpulse",

    # GStreamer codecs
    "gst-libav",
    "gst-plugins-bad",
    "gst-plugins-ugly",

    # Audio extras
    "easyeffects",
    "lsp-plugins"
]
