arch = [
	# CachyOS LTS kernel
	"linux-cachyos-lts",
	"linux-cachyos-lts-headers",

	# Drive utilities
	"btrfs-progs",

	# Security
	"apparmor",
	{ package = "apparmor.d-git", hooks = { after_install = [ "sudo", "systemctl", "enable", "apparmor.service" ] } },

	# Snapshotting
	"snapper",
	"snap-pac",

	# Limine utils.
	"limine-mkinitcpio-hook",
	"kernel-modules-hook",
	"limine-snapper-sync",
	
	# Network
	{ package = "networkmanager", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "NetworkManager.service" ] } },
	{ package = "ufw", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "ufw.service" ] } },
	"tufw",
    { package = "openssh", hooks = { after_install = [ "sudo", "systemctl", "enable", "sshd" ] } },

	# Package management helpers
	{ package = "reflector", hooks = { after_install = [ "sudo", "systemctl", "enable", "reflector.service" ] } },
	"pacman-contrib",
	"rebuild-detector",

	# Utilities
	"hwinfo",
	"fastfetch",
	"micro",
	"btop",
    "gdu",
	"duf",
	"bat",
	"bash-completion",
]
