arch = [
	# Drive utilities
	"btrfs-progs",

	# Security
	"apparmor",
	{ package = "apparmor.d-git", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "apparmor.service" ] } },

	# Snapshotting
	"snapper",
	"snap-pac",

	# Limine utils.
	"limine-mkinitcpio-hook",
	"limine-snapper-sync",
	
	# Network
	{ package = "networkmanager", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "NetworkManager.service" ] } },
	{ package = "ufw", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "ufw.service" ] } },
	"tufw",
    { package = "openssh", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "sshd" ] } },

	# Package management helpers
	"reflector",
	"pacman-contrib",
	"rebuild-detector",

	# Utilities
	"hwinfo",
	"fastfetch",
	"micro",
	"btop",
    "gdu",
	"duf",
	"bat",
	"bash-completion",
]
