arch = [
    { package = "ly", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "ly.service" ] } }, # Display manager

    # Tools
    "btrfs-assistant",
    "gparted",
    "xorg-xhost", # To make GParted work in Hyprland

    # File managers
    "yazi", # TUI
    "thunar", # GUI
    "catfish",
    "gvfs",
    "gvfs-mtp",
    "thunar-archive-plugin",
    "thunar-volman",

    # Thumbnails & previews
    "tumbler",
    "ffmpegthumbnailer",
    "libgsf",
    "poppler-glib",

    # Archiver
    "xarchiver",
    "7zip",
    "unrar",
    "unzip",
    "zip",

    # Apps
    "mpv", # Media player
    "viewnior",
    "legcord-bin", # Discord client
    "onlyoffice-bin", # Office suite
    "clipse", # Clipboard
    "code",
    "code-marketplace",

    # Gaming
    "steam",
    "gamescope",
    "protonup-qt",
    "prismlauncher",

    # GPU monitor and control
    { package = "lact", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "lactd" ] } },

    # Extra browser(s)
    "helium-browser-bin",
]
