arch = [
    { package = "ly", hooks = { after_install = [ "sudo", "systemctl", "enable", "ly.service" ] } }, # Display manager

    # Terminal emulator
    "kitty",

    # Tools
    "polkit-gnome",
    "btrfs-assistant",
    "gparted",
    "xorg-xhost", # To make GParted work in Hyprland
    { package = "lact", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "lactd" ] } }, # GPU monitor and control
    "nwg-look",

    # File managers
    "yazi", # TUI
    "thunar", # GUI
    "catfish",
    "gvfs",
    "gvfs-mtp",
    "thunar-archive-plugin",
    "thunar-volman",

    # Archiver
    "xarchiver",
    "7zip",
    "unrar",
    "unzip",
    "zip",

    # Thumbnails & previews
    "tumbler",
    "ffmpegthumbnailer",
    "libgsf",
    "poppler-glib",

    # Apps
    "firefox",
    "mpv", # Media player
    "viewnior",
    "equibop-bin", # Discord client
    "onlyoffice-bin", # Office suite
    "clipse", # Clipboard
    "vscodium",
    "vscodium-marketplace",
    "helium-browser-bin",

    # Gaming
    "steam",
    "gamescope",
    "protonup-qt",
    # "prismlauncher",
    "r2modman",
    "mangohud",
    "lib32-mangohud",
    "mangojuice",

    "wev", # Input debug
]
