arch = [
    # Clean up
    "rmlint",

    # Package management helpers
    "downgrade",
    "pacleaner",

    # Performance
    "realtime-privileges",
    
	# Power management
	"power-profiles-daemon",

	# Drive utilities
    { package = "smartmontools", hooks = { after_install = [ "sudo", "systemctl", "enable", "--now", "smartd" ] } },
    "udisks2",
    "udiskie",
    "rsync",
    "exfatprogs",
	"cryptsetup",

	# Network share
	"copyparty",
	"python-pillow",
	"python-pyftpdlib",
	"python-pyopenssl",

	# XDG
    { package = "xdg-user-dirs", hooks = { after_install = [ "xdg-user-dirs-update" ] } },

	# Optional extras
    "python-defusedxml",
    "python-packaging",
    "acpid",
    "wget",
]
