arch = [
    "hyprland",

    # Wayland support
    "qt5-wayland",
    "qt6-wayland",
    "xdg-desktop-portal-hyprland",
    "xdg-desktop-portal-gtk",

    # Services
    # "dunst",

    # Tools
    "nwg-displays", # Display management
    # "networkmanager-dmenu",

    # Clipboard
    "wl-clipboard",
    "wl-clip-persist"
]
